url: 'https://bell-boy.github.io'
baseurl: ''
title: "fbello" # the name of your site, e.g. ACME Corp.

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      usemathjax: true
      toc: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
  input: GFM

plugins:
  - jekyll-toc
